---
- name: Apache2 and Apache2 related packages installation
  become: true
  ansible.builtin.apt:
    name: 
      - apache2
      - libapache2-mod-php
    state: present

- name: Start Apache2 service
  become: true
  ansible.builtin.service:
    name: apache2
    state: started
  
- name: Enable Apache2 service 
  become: true
  ansible.builtin.service:
    name: apache2
    enabled: yes

- name: Check if link to default site exists
  ansible.builtin.stat:
    path: /etc/apache2/sites-enabled/000-default.conf
  register: link_check

- name: Run smoke test if default site exists
  ansible.builtin.uri:
    url: http://localhost
    return_content: yes
  register: smoke_test
  when: link_check.stat.islnk is defined

- name: Debug smoke test if default site exists
  ansible.builtin.debug:
    msg: "{{ smoke_test.content }}"
  when: smoke_test.content is defined