---
- name: Installing Visual C++ 2019 Redistributable Package
  hosts: windows-os:&azure-dr
  gather_facts: true
  tasks:
  - name: Download the Visual C++ 2019 Redistributable Package installer
    ansible.windows.win_get_url:
        url: https://aka.ms/vs/17/release/vc_redist.x64.exe
        dest: C:/vc_redist.x64.exe

  - name: Execute Installer
    ansible.windows.win_package:
        path: C:/vc_redist.x64.exe
        arguments: /quiet
        state: present

